### PR TITLE
Update NI to offline installers and add 7-zip to extract iso

### LINKED ISSUE #37: Change LabVIEW to offline installers
I like the tool and used it a lot last year. I see there are a number of changes already started for this year. I'm working with the beta since it looks like you've changed some file names to work with FTC that broke backward compatibility to last year's tool. I figured if I was going to have to work with source I might as well work with the new stuff. I like that you can pick items to include from a list, but I'd suggest switching LabVIEW from the online installer to the offline installer.

### PR DESCRIPTION
**Pull request by sciencewhiz**
Fixes #37

### CODE REVIEW

**Comment by JamieSinn** [comment]
I'd prefer to avoid adding 7zip as that's just a utility, but for week 1 I don't see an issue

**Comment by sciencewhiz** [comment]
Since the offline installers are ISO's, and not all computers have software to mount ISO's, that's why I included it.

**Comment by sciencewhiz** [comment]
Or the tool could extract ISO's 😉

**Comment by JamieSinn** [comment]
Windows 10 (which is the intended default target) can mount iso images on its own, so I'm not super worried.

**Pull request merged**
