### PR TITLE
Add limelight image

### PR DESCRIPTION
**Pull request by sciencewhiz**

### CODE REVIEW

**Comment by JamieSinn** [comment]
I can't support adding a media fire link, please use a direct link from limelight.

**Comment by sciencewhiz** [comment]
That is the direct link. From this page: https://limelightvision.io/pages/downloads

**Comment by sciencewhiz** [comment]
Is the concern about rehosting, or specifically about media fire?

**Comment by JamieSinn** [comment]
Both in combo.

**Comment by JamieSinn** [comment]
Looking at the download page, I'd much prefer not to host it here until limelight hosts it under their url. Similar to how rev has done it.

**Pull request closed without merging**
