### PR TITLE
Add instructions for use under MacOS

### PR DESCRIPTION
**Pull request by bovlb**
Partially resolve issue #50

### CODE REVIEW

**Comment by weaversam8** [comment]
In theory, this should run under dotnet core on MacOS, right? Parallels seems like it could be overkill

**Comment by bovlb** [comment]
> In theory, this should run under dotnet core on MacOS, right? Parallels seems like it could be overkill

I agree, and I tried that, but I couldn't get it to work.  I also tried running it inside a Docker container, but I don't know how to run it as a command-line tool.  After some time and effort, I found something that worked, so I documented it in case it was of benefit to others.  Coming to this project, I had no idea how I was supposed to use it, so I had to work it out from scratch.

**Comment by virtuald** [comment]
I think https://github.com/JamieSinn/CSA-USB-Tool/pull/86 would be a simpler solution for macOS/Linux.

**Comment by JamieSinn** [comment]
The plan I've got currently is to rewrite this to not require the Windows Forms library, which would allow dotnet core to be run on any platform, even in a CLI.

I hope to get around to that by week 3 ideally, but I definitely agree, docs suck on this!

**Comment by JamieSinn** [comment]
Given the next generation plans for this tool -  I think this can be closed for now

**Pull request closed without merging**
