### PR TITLE
Update FRCSoftware2024.csv

### PR DESCRIPTION
**Pull request by bovlb**
Partially resolves https://github.com/JamieSinn/CSA-USB-Tool/issues/120

* FRC Drive Connectivity Script
* PhotonVision images
* Elastic Dashboard

I did not include the radio kiosk as I was unable to generate a permanent direct download link.

### CODE REVIEW

**Comment by JamieSinn** [comment]
Sorry - but the FRC DriverStation Connectivity script is not something we're interested in including due to its political nature.

Photon Vision isn't something that really fits this tool - as it's something you need extremely specific setup in addition to the images; whereas the Limelight images work out of the box/are required for debugging.

For 2025's update this kind of tooling would be more team-focused - which I'm happy to include (whenever I finish the avalonia UI rewrite...)

**Comment by bovlb** [comment]
Thanks.

I was unaware that the FRC DriverStation Connectivity script had a political nature.  I haven't used it, but it's something I see recommended on CD, so was thinking of giving it a try next time that's an issue.  Should I remove it from my toolkit?

Photon Vision works surprisingly well out of the box, and the recent update is important because it purportedly resolves certain reliability/freezing issues.

What about Elastic Dashboard?  Teams often find themselves struggling with ShuffleBoard crashes at competition.

**Comment by sciencewhiz** [comment]
> I was unaware that the FRC DriverStation Connectivity script had a political nature. I haven't used it, but it's something I see recommended on CD, so was thinking of giving it a try next time that's an issue. Should I remove it from my toolkit?

It it were widespread, it would be classified by AV tools as a virus because it acts automatically and disables a whole bunch of security tools. 

It is convenient, but should always have the revert script used if it's ever used on anything that connects to the internet. My personal concern is that it gets used indiscriminately and not reverted and cause problems later that gets blamed on the CSA/FTAA/FTA that used it without understanding or explaining what it does and the consequences. Wider distribution makes it more likely that happens.

**Comment by JamieSinn** [comment]
> > I was unaware that the FRC DriverStation Connectivity script had a political nature. I haven't used it, but it's something I see recommended on CD, so was thinking of giving it a try next time that's an issue. Should I remove it from my toolkit?
> 
> It it were widespread, it would be classified by AV tools as a virus because it acts automatically and disables a whole bunch of security tools.
> 
> It is convenient, but should always have the revert script used if it's ever used on anything that connects to the internet. My personal concern is that it gets used indiscriminately and not reverted and cause problems later that gets blamed on the CSA/FTAA/FTA that used it without understanding or explaining what it does and the consequences. Wider distribution makes it more likely that happens.

100% agree.

**Comment by sciencewhiz** [comment]
> What about Elastic Dashboard?

https://github.com/wpilibsuite/WPILibInstaller-Avalonia/issues/423

**Comment by bovlb** [comment]
Anyone coming to this ticket because they want to put the latest PhotonVision release on their CSA key might find the following command useful:
```bash
mkdir photonvision
gh release download -p "*" -D photonvision -R PhotonVision/photonvision
```

**Pull request closed without merging**
