### PR TITLE
Update software list 2019

### PR DESCRIPTION
**Pull request by nstrik159**
Base update which includes Java, Python, and the NI cRIO Driver (which includes NI MAX 2)

### CODE REVIEW

**Comment by JamieSinn** [comment]
I assume Python would be to support robotpy teams?

**Comment by sciencewhiz** [comment]
Note that Java 11 is included in the wpilib offline installer, but installed to the wpilib location rather then global.

**Comment by nstrik159** [comment]
Yes it is @JamieSinn and thank you @sciencewhiz will remove the Java 11

**Comment by nstrik159** [comment]
@sciencewhiz Should be good now, thank you for letting me know!

**Comment by ThadHouse** [comment]
Is there something the NI driver gives that isn't gettable from the main LabVIEW installation. That extra 5GB download is very large.

**Comment by JamieSinn** [comment]
This is a good point. Didn't realize it was included in the LV install.

**Pull request merged**
